name: Deploy Laravel Rewards Site

on:
  push:
    branches:
      - main  # Deploy whenever code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          cd /home/deployer/as_rewards/rewards-site
          git pull origin main
          docker-compose up -d --build laravel  # Only build/restart the Laravel container
        EOF
